site_name: Dinoapp Documentation
site_url: https://gnucoop.github.io/docs.dinoapp.io/
theme:
  name: material
  language: en
extra:
  alternate:
    - name: English
      link: /docs.dinoapp.io/en/
      lang: en
    - name: Italiano
      link: /docs.dinoapp.io/it/
      lang: it
    - name: Español
      link: /docs.dinoapp.io/es/
      lang: es
    - name: Français
      link: /docs.dinoapp.io/fr/
      lang: fr
    - name: Português
      link: /docs.dinoapp.io/pt/
      lang: pt
    - name: Українська
      link: /docs.dinoapp.io/uk/
      lang: uk
    - name: العربية
      link: /docs.dinoapp.io/ar/
      lang: ar
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
